/** Versioned internal Career Suite pilot protocol (derived from docs/career-suite). */
export const INTERNAL_PILOT_RUNBOOK_SOURCE = {
  id: "career-suite-pilot-runbook",
  version: "2026-06-23",
  title: "Career Suite — P01 Operational Kit & Pilot Runbook",
  docPaths: [
    "docs/career-suite/P01-OPERATIONAL-KIT.md",
    "docs/career-suite/PILOT-RUNBOOK.md",
    "docs/career-suite/REAL-RESUME-PARSING.md",
  ],
  openingScript: [
    "Hoje estamos testando a ferramenta, não você.",
    "Eu não vou explicar antecipadamente como ela funciona. Quero observar o que você entende naturalmente.",
    "Durante o uso, fale em voz alta sobre o que está procurando, o que espera que aconteça e o que estiver confuso.",
    "Não existe resposta certa ou errada.",
    "Você pode parar a sessão a qualquer momento.",
    "O currículo e a vaga não serão usados para candidatura e não devem permanecer salvos depois da sessão.",
  ],
  neutralModeratorResponses: [
    "O que você esperaria que acontecesse?",
    "Faça o que parecer mais natural para você.",
    "O que você está procurando neste momento?",
  ],
  interventionTriggers: [
    "Bloqueio técnico declarado",
    "Risco de exposição de PII",
    "Participante tenta usar Production",
    "Sessão parada por mais de 2 minutos",
    "Erro P0",
  ],
  defaultTasks: [
    {
      id: "discovery",
      prompt: "Abra a ferramenta e me diga o que você entende que ela faz.",
      observe: ["proposta compreendida", "privacidade", "distinção análise vs candidatura"],
    },
    {
      id: "resume-input",
      prompt: "Use seu currículo como usaria normalmente.",
      observe: ["localização do campo", "colagem", "aviso de privacidade", "hesitação"],
    },
    {
      id: "resume-review",
      prompt: "(Observar) Revisão dos dados extraídos.",
      observe: ["disclosure aberto", "correções", "confiança no parser"],
    },
    {
      id: "resume-analysis",
      prompt: "Quando estiver pronto, continue como achar adequado.",
      observe: ["CTA", "loading", "score", "envio duplicado"],
    },
    {
      id: "result-interpretation",
      prompt: "Explique com suas palavras o que esse resultado está dizendo.",
      observe: ["pontos fortes", "atenção", "utilidade", "confiança"],
    },
    {
      id: "job-comparison",
      prompt: "Agora use uma vaga real que você consideraria.",
      observe: ["aderência", "lacunas", "próxima ação", "confusão com ATS"],
    },
    {
      id: "feedback",
      prompt: "Finalize da forma que achar adequada.",
      observe: ["consentimento", "envio de feedback", "privacidade"],
    },
  ],
  preflightChecklist: [
    "Preview autenticado aberto",
    "environment=preview confirmado",
    "pilot mode=true",
    "blockers=[]",
    "career_llm=false ou mock",
    "career_automation=false",
    "database=disabled",
    "providers=disabled",
    "GET /career-system/livez → 200",
    "GET /career-system/readyz → 200",
    "GET /career-system/health?probe=true → 200",
    "Formulário limpo — sem currículo ou resultado anterior",
    "localStorage/sessionStorage/IndexedDB verificados",
    "DevTools fechado para o participante",
    "Zoom 100%, viewport desktop normal",
    "Production intacta — não aberta",
  ],
  successCriteria: [
    "Fluxo principal concluído sem P0",
    "Zero P1 não resolvidos antes do próximo participante",
    "Participante compreende distinção análise vs candidatura",
    "Currículo e vaga não persistiram após limpeza",
    "Feedback respeita contrato de privacidade",
  ],
  severityMatrix: {
    P0: ["vazamento de PII", "persistência não consentida", "Production", "provider externo inesperado"],
    P1: [
      "fluxo principal incompleto com intervenção direta",
      "parsing materialmente incorreto",
      "score enganoso",
      "headings/skills/contato como bullets",
      "erro 4xx/5xx",
      "CTA bloqueado",
    ],
    P2: ["copy confusa", "densidade visual", "intervenção leve", "nomenclatura"],
    P3: ["preferência estética", "feature futura", "refinamento documental"],
  },
} as const;
